server:
  port: 8080  #配置访问端口
  servlet:
    context-path: /multi
    session:
      timeout: 5s
spring:
  datasource:
    url: jdbc:mysql://192.168.0.107:3306/tjun-training?characterEncoding=UTF-8
    data-username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
